# FIXME: This is a boilerplate file for environment secrets.
# Please replace the values with the actual secrets before using it in the workflow.
# The values must be base64 encoded.
apiVersion: v1
kind: Secret
metadata:
  name: environment-secret
data:
  arango-password: value-for-arango-password
